% Function to return the list of supported file formats and thier extensions.
function [desc, ext, aux] = getFileFormatReadList()

    desc = {'*.img - IMG file containing single band raster. Must have accompanying .lbl file.',...
            '*.cub - USGS ISIS format cub file. Must have accompanying .lbl file.',...
            '*.tif - TIFF image file. Must have accompanying .tfw worldfile.'};
    
	ext = {'img',...
           'cub',...
           'tif'};

	% Empty string means no auxilliary file needed.
    aux = {'lbl',...
           'lbl',...
           'tfw'};
end